### ISSUE TITLE
Ошибка при скачивании курса

### ISSUE THREAD

**Issue by klonwar** [limitedeternity/foxford_courses#13]
![image](https://user-images.githubusercontent.com/12374932/40279053-beb27e12-5c44-11e8-81d5-da3aa067b0b2.png)

Все на скрине. isMultiprocess is not defined

**Comment by limitedeternity** [comment]
Да, я исправил. Все теперь нормально.

**Comment by limitedeternity** [comment]
Ping @klonwar
