### ISSUE TITLE
Ссылка

### ISSUE THREAD

**Issue by Hollup** [limitedeternity/foxford_courses#14]
Материалы 2018г. Раздел Математика. Подготовка к ЕГЭ. Часть С, ссылка ведет на файлы для физики
А в разделе физики этого же года нерабочая ссылка на Я.Диск

**Comment by limitedeternity** [comment]
Ссылки действительно битые. Но все видео есть на канале в Телеграм, поэтому Вы можете взять их там.

**Comment by limitedeternity** [comment]
Ping @Hollup
