### ISSUE TITLE
Crush on screenshotes' making

### ISSUE THREAD

**Issue by kuzminovdmit** [limitedeternity/foxford_courses#2]
The screenshot's maker doesn't work properly. It had downloaded only first tasks in first 3 lessons, then it stopped on Foxford popup asking to give up. If I push it, it would crash with this:

> Traceback (most recent call last):
  File "C:\Users\kuzmi\Desktop\foxford_downloader\foxford_dl.py", line 85, in <module>
    selector()
  File "C:\Users\kuzmi\Desktop\foxford_downloader\foxford_dl.py", line 31, in selector
    downloader()
  File "C:\Users\kuzmi\Desktop\foxford_downloader\foxford_dl.py", line 67, in downloader
    operator(driver, course_link)
  File "C:\Users\kuzmi\Desktop\foxford_downloader\modules\operations\Operator.py", line 156, in operator
    driver.find_element_by_xpath("//div[contains(text(), 'Да')]").click()
  File "F:\Anaconda3\lib\site-packages\selenium\webdriver\remote\webelement.py", line 77, in click
    self._execute(Command.CLICK_ELEMENT)
  File "F:\Anaconda3\lib\site-packages\selenium\webdriver\remote\webelement.py", line 493, in _execute
    return self._parent.execute(command, params)
  File "F:\Anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "F:\Anaconda3\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Element <div>...</div> is not clickable at point (450, 951). Other element would receive the click: <div class="Modal__DialogOverlay__1oGEK">...</div>
  (Session info: chrome=60.0.3112.90)
  (Driver info: chromedriver=2.31.488763 (092de99f48a300323ecf8c2a4e2e7cab51de5ba8),platform=Windows NT 10.0.15063 x86_64)

**Comment by limitedeternity** [comment]
@kuzminovdmit 
Don't click. It said "element is not clickable", you see?
'cos you have already clicked on it.
Send crash report only if you haven't touched anything.

_Sent from my Xiaomi Redmi 3S using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by kuzminovdmit** [comment]
Sure I wouldn't. But it won't work without my click. And every shot except the first one comes with this, althought I didn't click anything.
> Ошибка, связанная с большой задержкой ответа. Попробуй еще раз.

**Comment by limitedeternity** [comment]
@kuzminovdmit 
Understood.
It's because delay is not enough.
Sure, I'll fix it. Later. Thanks.

_Sent from my Xiaomi Redmi 3S using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by limitedeternity** [comment]
By the way, any troubles with video download?

_Sent from my Xiaomi Redmi 3S using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by kuzminovdmit** [comment]
Well, I tried again. I waited for script reaction and it crushed with the same message, although I didn't click on foxford popup. I assume I'm not guilty. Videos had been processed but nothing was downloaded.

_Sent from my Meizu M5 Note using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by limitedeternity** [comment]
@kuzminovdmit 
Glad to hear, that videos are "ok".
I'll fix screenshots soon, as I said.
Try using v3, if you need videos only.

_Sent from my Xiaomi Redmi 3S using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by kuzminovdmit** [comment]
I have already reported in 2ch that old versions are stopping with oserror

_Sent from my Meizu M5 Note using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by limitedeternity** [comment]
@kuzminovdmit 
Try again.

_Sent from my Xiaomi Redmi 3S using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by limitedeternity** [comment]
There is no OTA, you know it right.
Clone repo again.

_Sent from my Xiaomi Redmi 3S using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by limitedeternity** [comment]
@kuzminovdmit 
То есть, говоришь, что первое задание дз фотографируется, а остальные - нет, или дз целого урока фотографируется, а остальные - нет?

_Sent from my Xiaomi Redmi 3S using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by kuzminovdmit** [comment]
Фотографируется первое ДЗ, затем есть попытки перейти на следующее, но он просто кидает запросы и пишет:
> Ошибка, связанная с большой задержкой ответа. Попробуй еще раз.

Кстати, в новой версии удалось пройти до 5 урока (раньше максимум до 4), но снова краш. А третья версия кидает ошибку, связанную с хромдрайвером, мол нужно в PATH экзешник прописать. Я попробую пофиксить сам сейчас.

**Comment by limitedeternity** [comment]
@kuzminovdmit 
Давай в телегу перейдем, мне там удобнее.
Ник тот же, что и здесь.

_Sent from my Xiaomi Redmi 3S using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by limitedeternity** [comment]
Issue closed. Homework fixed in v4(beta1)
